name: Java CI

on: [push]

jobs:
  buildAndTest:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build with Gradle
      run: ./gradlew build
    - name: Run JaCoCo
      run: ./gradlew jacocoTestReport
    - name: Modify gradle.properties for sonarqube secrets
      run: printf "sonar.projectKey=${{ secrets.sonar_projectKey }}\nsonar.organization=${{ secrets.sonar_organization }}\nsonar.host.url=${{ secrets.sonar_host_url }}\nsonar.login=${{ secrets.sonar_login }}" < gradle.properties
    - name: Read gradle.properties
      run: cat gradle.properties
    - name: Run sonarqube
      run: ./gradlew sonarqube
