name: Java CI

on: [push]

jobs:
  buildAndTest:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build with Gradle
      run: ./gradlew build
    - name: Run JaCoCo
      run: ./gradlew jacocoTestReport
    - name: Upload coverage reports
      run: bash <(curl -s https://codecov.io/bash) -t ${{ secrets.CODECOV_TOKEN }}
    - name: Modify gradle.properties for sonarqube secrets
      run: |
        echo "sonar.projectKey=${{ secrets.sonar_projectKey }}" << gradle.properties
        echo "sonar.organization=${{ secrets.sonar_organization }}" << gradle.properties
        echo "sonar.host.url=${{ secrets.sonar_host_url }}" << gradle.properties
        echo "sonar.login=${{ secrets.sonar_login }}" << gradle.properties
    - name: Run sonarqube
      run: ./gradlew sonarqube
