name: Java CI

on: [push]

jobs:
  buildAndTest:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build with Gradle
      run: ./gradlew build
    - name: Run JaCoCo
      run: ./gradlew jacocoTestReport
    - name: Modify gradle.properties for sonarqube secrets
      run: |
        tee -a gradle.properties <<< "sonar.projectKey=${{ secrets.sonar_projectKey }}"
        tee -a gradle.properties <<< "sonar.organization=${{ secrets.sonar_organization }}"
        tee -a gradle.properties <<< "sonar.host.url=${{ secrets.sonar_host_url }}"
        tee -a gradle.properties <<< "sonar.login=${{ secrets.sonar_login }}"
        cat gradle.properties
    - name: Run sonarqube
      run: ./gradlew sonarqube
